# Generated by Django 4.2.7 on 2023-12-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=15, verbose_name='Заголовок'),
        ),
    ]
