version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: db1
    volumes:
     - ./data/db:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis1
    expose:
      - 6379

  app:
    build: .
    container_name: app1
    env_file:
      - .env
    command: >
      bash -c "python manage.py migrate
      && python manage.py csu
      && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: celery_worker1
    env_file:
      - .env
    depends_on:
      - redis
      - app
    command: celery -A config worker -l INFO

  celery_beat:
    build: .
    container_name: celery_beat1
    env_file:
      - .env
    depends_on:
      - celery_worker
    command: celery -A config beat -l INFO